apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flight-data-pipeline

resources:
  - namespace.yaml
  - configmap.yaml
  - mongodb-headless-service.yaml
  - mongodb-service.yaml
  - mongodb-statefulset.yaml
  - backend-service.yaml
  - backend-deployment.yaml
  - frontend-service.yaml
  - frontend-deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: flight-data-pipeline
      app.kubernetes.io/version: v1.0.0-rc.3
    includeSelectors: false
    includeTemplates: true
