apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-config
data:
  KAFKA_BOOTSTRAP_SERVERS: kafka:29092
  KAFKA_TOPIC: aircraft.positions.raw.v1
  POLL_INTERVAL_SECONDS: "120"
  MAX_POLLS: "0"
  OPENSKY_AREA_MODE: global
